name: royalgroup
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.2.0 <3.0.0"
dependencies:
  flutter_native_splash: ^0.1.9
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.0.1
  #firebase_core: ^0.4.4+3
  #cloud_firestore: ^0.13.5
  #firebase_auth: ^0.16.0
  modal_progress_hud: ^0.1.3
  http: ^0.12.1
  flutter_spinkit: ^4.1.2
  local_auth: ^0.6.2+2
  path_provider: ^1.6.8
  shared_preferences: ^0.5.7+2
  font_awesome_flutter: ^8.8.1
  carousel_pro: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_native_splash:
  image: images/android-logo.png
  color: "424242"
  android_disable_fullscreen: true